#!/usr/bin/env bash
echo "---- Executing catalog_exec"
# pushd $HOME/Code/grpr
git fetch
git pull
echo "catalog_exec : "$(pwd)
pushd docker/gppy
make catalog
make exec-catalog
popd
echo "---- Exiting catalog_exec"