#!/usr/bin/env bash
echo "---- Executing kurgan_exec"
# pushd $HOME/Code/grpr
git fetch
git pull
echo "kurgan_exec : "$(pwd)
pushd docker/gppy
make image-catalog
make exec-catalog
popd
echo "---- Exiting kurgan_exec"