#!/usr/bin/env python3

import os
import json
import time
from pathlib import Path

from gpm.generate import Generator
from gpm.db import Database

if __name__ == "__main__":
    print("-------- Entering gppy_playgen")
    db = Database()
    sources = Path(os.getenv("FLACSRCS"))
    print(sources)
    playlists = Path(os.getenv("PLAYLISTS"))
    print(playlists)
    diskard = Generator(source=sources, target=db)
    print("--------  Exiting gppy_playgen")
