#!/usr/bin/env python3

import os
from typing import Dict
from pathlib import Path

from mutagen.mp3 import MP3
from mutagen.id3 import ID3
from mutagen.flac import FLAC, StreamInfo

AUDIO_FORMATS = [".mp3", ".flac"]
PLAYLIST_FORMATS = [".m3u"]


def flac_tags(spath: Path) -> Dict[str, str]:
    """Return the tags from a FLAC file"""
    retval: Dict[str, str] = {}
    libf = LibFile(spath)
    flak = FlacFile(libf)
    flak.debug()
    # genre = flak["genre"]
    # idthree = ID3(spath)
    # print(idthree.pprint())
    # retval["length"] = int(mpthree.info.length)
    # retval["artist"] = idthree["TPE1"].text[0]
    # retval["disc"] = idthree["TPOS"].text[0]
    # retval["track"] = idthree["TRCK"].text[0]
    # try:
    #     retval["date"] = idthree["TDRC"].text[0]
    # except KeyError:
    #     print(idthree.pprint())
    #     retval["date"] = "1962-12-22"
    # retval["album"] = idthree["TALB"].text[0]
    # retval["title"] = idthree["TIT2"].text[0]
    # retval["genre"] = idthree["TCON"].text[0]
    # try:
    #     retval["composer"] = idthree["TCOM"].text[0]
    # except KeyError:
    #     retval["composer"] = "Unknown"
    return retval


def mp3_tags(spath: Path) -> Dict[str, str]:
    """Return the ID3 tags from an MP3 file"""
    retval: Dict[str, str] = {}
    mpthree = MP3(spath)
    idthree = ID3(spath)
    # print(idthree.pprint())
    retval["length"] = int(mpthree.info.length)
    retval["artist"] = idthree["TPE1"].text[0]
    retval["disc"] = idthree["TPOS"].text[0]
    retval["track"] = idthree["TRCK"].text[0]
    try:
        retval["date"] = idthree["TDRC"].text[0]
    except KeyError:
        print(idthree.pprint())
        retval["date"] = "1962-12-22"
    retval["album"] = idthree["TALB"].text[0]
    retval["title"] = idthree["TIT2"].text[0]
    retval["genre"] = idthree["TCON"].text[0]
    try:
        retval["composer"] = idthree["TCOM"].text[0]
    except KeyError:
        retval["composer"] = "Unknown"
    return retval


def tags(spath: Path) -> Dict[str, str]:
    if spath.suffix == ".flac":
        return flac_tags(spath)
    return mp3_tags(spath)


def walk(spath: Path):
    """Some stuff"""
    for path in sorted(spath.iterdir(), reverse=False):
        if path.is_dir():
            print(path)
            yield from walk(path)
            continue
        yield path.resolve()


def scan(source: Path):
    """Run here"""
    for fyle in walk(spath=source):
        if fyle.suffix in AUDIO_FORMATS:
            # print(fyle)
            pass


if __name__ == "__main__":
    print("-------- Entering gppy_py")
    sources = Path(os.getenv("FLACSRCS"))
    print(sources)
    playlists = Path(os.getenv("PLAYLISTS"))
    print(playlists)
    scan(source=sources)
    print("--------  Exiting gppy_py")
