#!/usr/bin/env python3

import os
import json
import time
from pathlib import Path

from gpm.generate import Generator
from gpm.db import Database

MUSIC = Path("/netmnt/Audio/Music")

if __name__ == "__main__":
    print("-------- Entering gppy_playgen")
    db = Database()
    playlists = MUSIC
    print(playlists)
    diskard = Generator(target=playlists, source=db)
    print("--------  Exiting gppy_playgen")
