[metadata]
name = grpr
version = 0.0.1
author = Jeremy Pavier
author_email = grid.presence@gmx.com
description = CLI toolkit for developers
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Programming Language :: Python :: 3
    License :: MIT
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8
install_requires = 
    typer[all]
    packaging

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    grpr = grpr.__main__:main
